### ISSUE TITLE
date_range in European format

### ISSUE THREAD

**Issue by thecpshah** [AileenNielsen/TimeSeriesAnalysisWithPython#2]
I was following the video and tried to generate date_range in European format but the argument `dayfirst = True` does not work.

```
import pandas as pd

rng1 = pd.date_range('1/7/2016', periods = 10)
rng2 = pd.date_range('1/7/2016, periods = 10, dayfirst = True)
```

Both `rng1` and `rng2` are equal.

**Comment by AileenNielsen** [comment]
Thank you for the pull request. I corrected the notebook. I should have specified that pd.to_datetime, not pd.date_range. Notebook now appears as seen in screen shot.
<img width="986" alt="screen shot 2016-07-26 at 11 02 10 am" src="https://cloud.githubusercontent.com/assets/20178066/17143246/c471df02-5320-11e6-8144-de804870d646.png">

**Comment by thecpshah** [comment]
Thanks Aileen!

**Comment by AileenNielsen** [comment]
My pleasure. Please let me know if you spot anything else!
