### ISSUE TITLE
10 minutes pandas

### ISSUE THREAD

**Issue by sperezconesa** [AileenNielsen/TimeSeriesAnalysisWithPython#3]
Dear doc. Nielsen,
I have been watching the Time Series Analysis lecture on youtube, which is fantastic by the way, and I am very interested in the notebook 0 on the 10 min introduction to pandas. I cannot find it on the web... Could you please post it in this repository?
Thank you very much!
Best regards,
Sergio

**Comment by atulsaurav** [comment]
The repository has a zipfile called - SciPyTimeSeries.zip. The 10 mins to pandas notebook is present there.

Thanks!

**Comment by sperezconesa** [comment]
Thank you! :)
